services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: varshithgowdav
      POSTGRES_PASSWORD: Leela@1422
      PGDATA: data/postgres
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
