server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    username: varshith
    password: 12345
    url: jdbc:postgresql://54.82.96.15:5432/customer
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet